name: Build LaTeX document
on: [push]
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v1
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@master
        with:
          root_file: research/progress/main.tex
          working_directory: research/progress
          args: -pdf -file-line-error -interaction=nonstopmode -shell-escape
